afisha/afisha/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', views.NewsView.as_view()),
    path('national/', views.NationalView.as_view()),
    path('children/', views.ChildrenView.as_view()),
    path('movie/',views.MovieListView.as_view()),
    path('movie/<int:pk>', views.MovieDetailView.as_view()),
    path('category/<int:category_id>/movie/', views.CategoryMovieFilterView.as_view()),
    path('add_movie/',views.AddMovieFormView.as_view()),
    path('add_director/',views.AddDirectorFormView.as_view()),
    path('register/',views.RegisterFormView.as_view()),
    path('login/',views.LoginView.as_view()),
    path('logout/', views.LogoutView.as_view()),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)




#if settings.DEBUG:
  #  urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

afisha/main/models.py
from django.db import models
from datetime import date
# Create your models here.
#from django.utils.safestring import mark_safe


class Category(models.Model):
    class Meta:
        verbose_name='Категория'
        verbose_name_plural = 'Категории'

    objects = None
    name=models.CharField(max_length=150,unique=True,verbose_name='Название')

    def __str__(self):
        return self.name



class Actor(models.Model):
    class Meta:
        verbose_name='Астер'
        verbose_name_plural='Акторы'
    name = models.CharField(max_length=100,verbose_name="Название")
    age = models.PositiveIntegerField(default=0,verbose_name="Возраст")
    image = models.ImageField(upload_to='actors',verbose_name="Картинка")

    def __str__(self):
        return self.name



class Director(models.Model):
    class Meta:
        verbose_name='Режиссер'
        verbose_name_plural='Режиссеры'
    name = models.CharField(max_length=100,verbose_name="Название")

    def __str__(self):
        return self.name



class Movie(models.Model):
    class Meta:
        verbose_name='фильм'
        verbose_name_plural='фильмы'
    objects = None
    tittle = models.CharField(max_length=1000,unique=True,verbose_name="Название")
    description = models.TextField(blank=True,verbose_name="Описание фильмы")
    year = models.PositiveSmallIntegerField(default=2000,verbose_name="Год")
    image = models.ImageField(upload_to='image', null=True,verbose_name="Картинка")
    directors = models.ForeignKey(Director, on_delete=models.SET_NULL, blank=True, null=True,
                                  verbose_name="Режиссеры")
    actors = models.ManyToManyField(Actor, max_length=100,verbose_name="Актеры")
    created_at = models.DateTimeField(auto_now_add=True,verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now_add=True,verbose_name="Дата изменения")
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True,verbose_name="Категория"
    )

    def __str__(self):
        return self.tittle
    @property
    def actors_list(self):
        return ''.join([actors.name for actors in self.actors.all()])



class Review(models.Model):
    class Meta:
        verbose_name='отзыв'
        verbose_name_plural='отзывы'
    objects = None
    text = models.TextField(verbose_name="Текст отзыва")
    author = models.CharField(max_length=100, null=True, blank=True, default='')
    #email = models.EmailField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='reviews',
    verbose_name='Фильм')

    def __str__(self):
        return f"{self.author}-{self.movie}"




afisha/templates/add_director.html
{% extends 'layout.html' %}

{% block content %}
    <h3 style="padding -left:200px">Info about directors </h3>
    <form action ="/add_director/" method="post" style="padding left:200px; padding right:200px">
        { % csrf_token%}
        {{ form.as_p}}
        <input type="submit" class="btn btn-primary" value="send ">
    </form>



{% endblock %}

afisha/templates/add_movie.html
{% extends 'layout.html' %}

{% block content %}
    <div class="form-content">
        <h3>Create movie</h3>
        <form action="/add_movie/" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-danger" value="send">
        </form>
    </div>
{% endblock %}

afisha/templates/children.html
{% extends 'layout.html' %}

{%  block content %}
     <h1>Best cartoons</h1>
     <h2 style="color:{{color}}"> {{key}}</h2>
     {% for name in list_ %}
         < p{ %if name =='Maikraft' %} style="color: brown" {% endif %} >{{ name }} < /p >
     {%endfor%}
{% endblock %}

afisha/templates/detail.html
{% extends%}
<h2>Title:{{movie_detail.name}}}</h2>
<p>Description:{{movie_detail.description}}</p>
<p>Created Date:{{movie_detail.created_at}}</p>
<hr/>
<h3>All reviews</h3>
{% for review in movie_detail.reviews.all%}
    <p>{{review.text}}</p>
    <p>{{review.author}}</p>
    <hr>
{% endfor %}

afisha/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie List</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Main Page</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/movie/">All movies</a>
                </li>
                {% for category in category_list %}
                    <li class="nav-item">
                        <a class="nav-link" href="/category/{{ category.id }}/movie/">{{ category.name }}</a>
                    </li>
                {% endfor %}
                <li class="nav-item">
                    <a class="nav-link" href="/add_movie/">Create movie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/add_director/">Info about director</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/register/"> Registration </a>
                </li>
                {% if user.is_anonymous%}
                <li class="nav-item">
                    <a class="nav-link" href="/login/">Authorization </a>
                </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="/logout/">Exit({{user.username}}) </a>
                  </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

afisha/templates/login.html
{% extends 'layout.html' %}

{% block content %}
    <div class="form-content">
        <h3>Authorization</h3>
        <form action="/login/" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="send" class="btn btn-info">
        </form>
    </div>
{% endblock %}

afisha/templates/movie.html
{% extends 'layout.html'%}

{% block content %}

    <h1>Movies list</h1>
    {% for movie in movie_list%}
        {%  if actors.image %}
            <img src="{{ product.image.url}}"alt="" style=" width:200px">
        {% endif%}

        <a href="/movie/{{movie.id}}/">Title:{{movie.name}}}</a>
        <p>Created Date:{{movie.created_at}}</p>
        <p>Category:{{movie.category.name}}</p>
        <hr/>
    {% endfor %}

{% endblock %}

afisha/templates/national.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Our stars</title>
</head>
<body>
<h1>Our national actress and actor</h1>
</body>
</html>

afisha/templates/news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>News about films in Kyrgyzstan</title>
</head>
<body>
<h1>Today we are going to talk about new films </h1>
<h2 style="color:{{color}}">{{key}}</h2>
{% for name in list_%}
   <p>{{name}}</p>
{% endfor%}
</body>
</html>

afisha/templates/register.html
{% extends 'layout.html'%}

{% block  content %}
    <div class ="form-content">
        <h3>Registration </h3>
        <form action ="/register/" method="post">
             {% csrf_token %}
             {{form.as_p}}
             <input type ="submit" value ="Send" class="btn btn-warning ">
        </form>
    </div>
{% endblock%}